# Generated by Django 5.0.2 on 2024-02-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
