# Generated by Django 5.0.2 on 2024-02-12 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_useritem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user_id',
        ),
    ]
